version: '3'
services:
  zookeeper:
    image: 'confluentinc/cp-zookeeper:7.3.0'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    networks:
      - entity_net
  kafka:
    image: 'confluentinc/cp-kafka:7.3.0'
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    healthcheck:
      test: kafka-topics --bootstrap-server localhost:9092 --list || exit 1
      interval: 10s
      timeout: 5s
      retries: 9
    networks:
      - entity_net
  mongo:
    image: 'mongo:4.4.14'
    restart: 'always'
    ports:
      - '27017:27017'
    networks:
      - entity_net
    # volumes:
    #   - mongo-data:/data/db
    logging:
      driver: none
  entity_management:
    image: shikshalokamqa/elevate-entity-management:3.3.13.1
    ports:
      - '5001:5001'
    command: ['nodemon', 'app.js']
    env_file:
      - ./entity_management_env
    depends_on:
      - mongo
    volumes:
      - ./config.json:/var/src/config.json
    networks:
      - entity_net

networks:
  entity_net:
    # external: false
volumes:
  mongo-data:
  logs:
